Update to wgpu 27.0.1, wgpu-profiler 0.25 (#1280)
Bumped the MSRV to 1.88 and updated wgpu and wgpu-profiler.

Unfortunately I was unable to run the tests because of this error in
libdeflate-sys:
```
cargo:warning=libdeflate/lib/x86/adler32_template.h:295:14: error: always_inline function '_mm512_dpbusd_epi32' requires target feature 'avx512vnni', but would be inlined into function 'adler32_x86_avx512_vl512_vnni' that is compiled without support for 'avx512vnni'
  cargo:warning=  295 |                                 v_s2   = VDPBUSD(v_s2,   data_a, mults);
  cargo:warning=      |                                          ^
  cargo:warning=libdeflate/lib/x86/adler32_template.h:109:28: note: expanded from macro 'VDPBUSD'
  cargo:warning=  109 | #  define VDPBUSD(a, b, c)      _mm512_dpbusd_epi32((a), (b), (c))
  ...
```
It seems like oxipng depends on libdeflater, and libdeflater hasn't had
a release in a while.

However vello seems to compile succesfully and I am able to run my other
project with this branch as a dependency.