vello_common: Remove failing test (#1740)
This test fails since #1714, the reason is that since the PR we ensure
that no zero-width strips can be emitted at places other than the row
end.

```
---- clip::tests::row_iterator_zero_width_alpha_region stdout ----

thread 'clip::tests::row_iterator_zero_width_alpha_region' (957770) panicked at sparse_strips/vello_common/src/clip.rs:549:17:
zero-width strips must only appear at the end of a row
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    clip::tests::row_iterator_zero_width_alpha_region
```

This is true for our current strip generation code, so the assertion is
correct, but of course in a unit test it's still possible to manually
construct such strip. The reason this wasn't caught in the PR is that we
run tests in release mode now. :( We should probably consider running at
least the `vello_common` (and maybe `vello_cpu`) unit tests in debug
mode in CI.