Fix `vello_sparse_tests` GPU tests for `cargo test`
On some platforms, running the GPU tests in parallel crashes the testing
process more often than not. This "fixes" it for `cargo test` and leaves
`cargo nextest` mostly unimpacted.

```bash
$ cargo test --package vello_sparse_tests
# ...
error: test failed, to rerun pass `-p vello_sparse_tests --test tests`

Caused by:
  process didn't exit successfully: `[snip]/vello/target/debug/deps/tests-704ef390c4f325bc` (signal: 11, SIGSEGV: invalid memory reference)
```