Don't enable WGPU in std (#1822)
Today, it's impossible to enable `std` and `webgl` without seeing this
error: "Both WebGL and wgpu with the "webgl" feature are enabled"
because WGPU is enabled via `std`.